apiVersion: v1
kind: ConfigMap
metadata:
  name: wazuh-app-config
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh-ai-companion
    app.kubernetes.io/component: config
data:
  APP_NAME: "Wazuh AI Companion"
  APP_VERSION: "2.0.0"
  ENVIRONMENT: "production"
  DEBUG: "false"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "*"
  API_PREFIX: "/api/v1"
  
  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "wazuh_chat"
  DB_USER: "postgres"
  DB_POOL_SIZE: "10"
  DB_MAX_OVERFLOW: "20"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "20"
  
  # AI Configuration
  OLLAMA_HOST: "ollama-service"
  OLLAMA_PORT: "11434"
  OLLAMA_MODEL: "llama3"
  EMBEDDING_MODEL: "all-MiniLM-L6-v2"
  CHUNK_SIZE: "500"
  CHUNK_OVERLAP: "50"
  MAX_TOKENS: "2048"
  TEMPERATURE: "0.7"
  
  # Log Processing Configuration
  WAZUH_LOGS_PATH: "/var/ossec/logs/archives"
  DEFAULT_DAYS_RANGE: "7"
  MAX_DAYS_RANGE: "365"
  SSH_TIMEOUT: "10"
  LOG_BATCH_SIZE: "1000"
  
  # Security Configuration
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  PASSWORD_MIN_LENGTH: "8"
  BCRYPT_ROUNDS: "12"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh-ai-companion
    app.kubernetes.io/component: nginx
data:
  nginx.conf: |
    events {
        worker_connections 2048;
        use epoll;
        multi_accept on;
    }

    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;

        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=auth:10m rate=5r/s;

        upstream app {
            least_conn;
            server wazuh-app-service:8000 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }

        server {
            listen 80;
            server_name _;

            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options nosniff always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy strict-origin-when-cross-origin always;

            client_max_body_size 10M;

            location /ws {
                proxy_pass http://app;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 86400;
                limit_req zone=api burst=20 nodelay;
            }

            location ~ ^/api/v1/auth/ {
                proxy_pass http://app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                limit_req zone=auth burst=10 nodelay;
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }

            location /api/ {
                proxy_pass http://app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                limit_req zone=api burst=50 nodelay;
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }

            location /health {
                proxy_pass http://app/health;
                access_log off;
            }

            location / {
                proxy_pass http://app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                limit_req zone=api burst=30 nodelay;
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: wazuh
  labels:
    app.kubernetes.io/name: wazuh-ai-companion
    app.kubernetes.io/component: redis
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    loglevel notice
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb